server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/tasklist"
    username: paf2024
    password: paf2024
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

logging:
  level:
    org:
      springframework: INFO
      springframework.web: INFO
      springframework.jpa: INFO
      hibernate: WARN
      hibernate.SQL: WARN
      hibernate.type: WARN
    de:
      vfh:
        paf:
          tasklist: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

tasklist:
  scheduling:
    notification-check-minutes: 1
    task-check-seconds: 20
  concurrent:
    thread-pool-size: 5
    max-queue-size: 100
  app-name: "Task List Application"