# Node.js with Vue
# Build and deploy a Vue.js application to Azure App Service

trigger:
  - main

pool: 'Self hosted agent pool'

parameters:
- name: deployOnServer
  displayName: Deploy on Server
  type: boolean
  default: true

variables:
  nodeVersion: '18.x'
  buildConfiguration: 'production'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js $(nodeVersion)'
    inputs:
      versionSpec: '$(nodeVersion)'

  - task: Npm@1
    displayName: 'NPM Install'
    inputs:
      command: 'install'
      workingDir: 'PatternsAndFrameworks_Frontend'

  - task: Npm@1
    displayName: 'NPM Build'
    inputs:
      command: 'custom'
      workingDir: 'PatternsAndFrameworks_Frontend'
      customCommand: 'run build'

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      containerRegistry: 'sc_acr_bht_sarah_sp'
      command: 'login'

  - task: Docker@2
    displayName: Docker build - Frontend
    inputs:
      containerRegistry: 'sc_acr_bht_sarah_sp'
      repository: 'PAF2024_Frontend'
      command: 'build'
      Dockerfile: 'PatternsAndFrameworks_Frontend/Dockerfile'
      buildContext: 'PatternsAndFrameworks_Frontend'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: Docker push - Frontend
    inputs:
      containerRegistry: 'sc_acr_bht_sarah_sp'
      repository: 'PAF2024_Frontend'
      command: 'push'
      tags: |
        $(Build.BuildId)
        latest

  - ${{ if eq(parameters.deployOnServer, true) }}:
    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure App Service Deploy: paf2024-frontend'
      inputs:
        azureSubscription: sc_arm_sp-auto_bhtsarah
        appType: webAppContainer
        WebAppName: 'paf2024-frontend'
        deployToSlotOrASE: true
        ResourceGroupName: 'rg_infrastructure'
        DockerNamespace: bhtsarah.azurecr.io
        DockerRepository: PAF2024_Frontend
        DockerImageTag: '$(Build.BuildId)'