package de.vfh.paf.tasklist.domain.service;

import de.vfh.paf.tasklist.domain.model.TaskStatus;
import de.vfh.paf.tasklist.domain.model.Task;
import de.vfh.paf.tasklist.domain.model.TaskQueue;
import de.vfh.paf.tasklist.domain.model.TaskResult;
import de.vfh.paf.tasklist.domain.repository.TaskRepository;
import de.vfh.paf.tasklist.domain.repository.TaskResultRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@ActiveProfiles("test")
@Import({TaskQueueService.class, TaskService.class, de.vfh.paf.tasklist.presentation.websocket.TaskWebSocketController.class})
class TaskQueueServiceTest {

    @Autowired
    private TaskQueueService taskQueueService;

    @Autowired
    private TaskRepository taskRepository;

    @Autowired
    private TaskResultRepository taskResultRepository;

    @Autowired
    private TaskService taskService;

    @BeforeEach
    void setUp() {
        taskRepository.deleteAll();
        taskResultRepository.deleteAll();
    }

    @Test
    void shouldCreateTaskQueue() {
        // Arrange
        String queueName = "Test Queue";

        // Act
        TaskQueue queue = taskQueueService.createQueue(queueName);

        // Assert
        assertNotNull(queue);
        assertEquals(queueName, queue.getName());
        assertEquals(0, queue.getTasks().size());
    }

    @Test
    void shouldEnqueueTask() {
        // Arrange
        TaskQueue queue = taskQueueService.createQueue("Test Queue");
        Task task = taskService.createRunnableTask("Test Task", "Description", LocalDateTime.now().plusDays(1), 100, "de.vfh.paf.tasklist.domain.tasks.CalculatePiTask"
        );

        // Act
        boolean enqueued = taskQueueService.enqueueTask(queue.getId(), task.getId());

        // Assert
        assertTrue(enqueued);
        assertEquals(1, queue.getTasks().size());
        assertEquals(task.getId(), queue.getTasks().getFirst().getId());

        // Verify task status was updated
        Task updatedTask = taskRepository.findById(task.getId()).orElseThrow();
        assertEquals(TaskStatus.QUEUED, updatedTask.getStatus());
    }

    @Test
    void shouldExecuteTask() throws Exception {
        // Arrange
        TaskQueue queue = taskQueueService.createQueue("Test Queue");
        Task task = taskService.createRunnableTask("Test Task", "Description", LocalDateTime.now().plusDays(1), 100, "de.vfh.paf.tasklist.domain.tasks.CalculatePiTask");
        taskQueueService.enqueueTask(queue.getId(), task.getId());

        // Act
        CompletableFuture<TaskResult> futureResult = taskQueueService.executeNextTask(queue.getId(),
                (t) -> {
                    TaskResult result = new TaskResult();
                    result.setTitle("Current Time");
                    result.setContent(LocalDateTime.now().toString());
                    result.setTaskId(t.getId());
                    result.setTimestamp(LocalDateTime.now());
                    return result;
                });

        // Wait for the result with a timeout
        TaskResult result = futureResult.get(5, TimeUnit.SECONDS);

        // Assert
        assertNotNull(result);

        // With the migration to JPA, the task ID is now generated by the database
        // So we can't check for an exact match, but we can check it's not null
        assertNotNull(result.getTaskId());
        assertEquals("Current Time", result.getTitle());

        // Verify task status
        Task updatedTask = taskRepository.findById(task.getId()).orElseThrow();
        assertEquals(TaskStatus.DONE, updatedTask.getStatus());
    }

    @Test
    void shouldProcessAllTasksInQueue() throws Exception {
        // Arrange
        TaskQueue queue = taskQueueService.createQueue("Test Queue");

        Task task1 = taskService.createRunnableTask("Task 1", "Description", LocalDateTime.now().plusDays(1), 100, "de.vfh.paf.tasklist.domain.tasks.CalculatePiTask"
        );
        Task task2 = taskService.createRunnableTask("Task 2", "Description", LocalDateTime.now().plusDays(1), 100, "de.vfh.paf.tasklist.domain.tasks.CalculatePiTask"
        );
        Task task3 = taskService.createRunnableTask("Task 3", "Description", LocalDateTime.now().plusDays(1), 100, "de.vfh.paf.tasklist.domain.tasks.CalculatePiTask"
        );

        taskQueueService.enqueueTask(queue.getId(), task1.getId());
        taskQueueService.enqueueTask(queue.getId(), task2.getId());
        taskQueueService.enqueueTask(queue.getId(), task3.getId());

        // Act
        List<TaskResult> results = taskQueueService.processAllTasks(queue.getId(),
                (t) -> {
                    TaskResult result = new TaskResult();
                    result.setTitle("Result for " + t.getTitle());
                    result.setContent("Success");
                    result.setTaskId(t.getId());
                    result.setTimestamp(LocalDateTime.now());
                    return result;
                }).get(5, TimeUnit.SECONDS);

        // Assert
        assertEquals(3, results.size());

        // Check results
        for (TaskResult result : results) {
            assertTrue(result.getTitle().startsWith("Result for Task"));
            assertEquals("Success", result.getContent());
        }

        // Verify all tasks are completed
        assertEquals(TaskStatus.DONE, task1.getStatus());
        assertEquals(TaskStatus.DONE, task2.getStatus());
        assertEquals(TaskStatus.DONE, task3.getStatus());

        // Verify queue is empty
        assertEquals(0, queue.getTasks().size());
    }
}